<?php

/**
 * Implements hook_permission().
 */
function aakb_writing_competition_permission() {
  return array(
    'access writing competition' => array(
      'title' => t('Access writing competition'),
      'description' => t('See competition settings and contributes.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function aakb_writing_competition_menu() {
  $item = [];

  $item['skrivekonkurrence'] = [
    'title' => _aakb_writing_competition_t('Writing competition'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['aakb_writing_competition_form'],
    'access callback' => TRUE,
  ];

  $item['admin/config/ding/competition'] = [
    'title' => _aakb_writing_competition_t('Writing competition'),
    'description' => t('See competition settings and contributes.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['aakb_writing_competition_admin'],
    'access arguments' => ['access writing competition'],
    'file' => 'includes/aakb_writing_competition.admin.inc'
  ];

  return $item;
}

/**
 * Implements hook_form().
 */
function aakb_writing_competition_form($form, &$form_state) {
  $form = [];

  $form['type'] = [
    '#type' => 'select',
    '#title' => _aakb_writing_competition_t('Type'),
    '#description' => _aakb_writing_competition_t('Select who you are?'),
    '#options' => [
      'parent' => _aakb_writing_competition_t('Parent'),
      'teacher' => _aakb_writing_competition_t('Teacher'),
    ],
    '#required' => TRUE,
  ];

  $form['parent'] = [
    '#type' => 'fieldset',
    '#title' => _aakb_writing_competition_t('Parent information'),
    '#description' => 'TEXT TEXT TEXT',
    '#tree' => TRUE,
    '#states' => [
      'visible' => array(
        ':input[name="type"]' => array(
          'value' => 'parent',
        ),
      ),
    ],
  ];

  $form['parent']['name'] = [
    '#type' => 'textfield',
    '#title' => _aakb_writing_competition_t('Parent name'),
  ];

  $form['parent']['mail'] = [
    '#type' => 'textfield',
    '#title' => _aakb_writing_competition_t('Parent e-mail-address'),
  ];

  $form['teacher'] = [
    '#type' => 'fieldset',
    '#title' => _aakb_writing_competition_t('Teacher information'),
    '#description' => 'TEXT TEXT TEXT',
    '#tree' => TRUE,
    '#states' => [
      'visible' => array(
        ':input[name="type"]' => array(
          'value' => 'teacher',
        ),
      ),
    ],
  ];

  $form['teacher']['name'] = [
    '#type' => 'textfield',
    '#title' => _aakb_writing_competition_t('Teacher name'),
  ];

  $form['teacher']['mail'] = [
    '#type' => 'textfield',
    '#title' => _aakb_writing_competition_t('Teacher e-mail-address'),
  ];

  $form['teacher']['grade'] = [
    '#type' => 'textfield',
    '#title' => _aakb_writing_competition_t('Grade'),
  ];

  $form['contribution'] = [
    '#type' => 'fieldset',
    '#title' => _aakb_writing_competition_t('Contribution')
  ];

  $form['contribution']['name'] = [
    '#type' => 'textfield',
    '#title' => _aakb_writing_competition_t('Name'),
    '#required' => TRUE,
  ];

  $form['contribution']['age'] = [
    '#type' => 'textfield',
    '#title' => _aakb_writing_competition_t('Age'),
    '#required' => TRUE,
  ];

  $form['contribution']['text'] = [
    '#type' => 'textarea',
    '#title' => _aakb_writing_competition_t('Text'),
    '#required' => TRUE,
    '#maxlength_js' => TRUE,
    '#maxlength' => 500,
  ];

  $form['submit'] = [
    '#type' => 'submit',
    '#value' => _aakb_writing_competition_t('Submit'),
  ];

  return $form;
}

function aakb_writing_competition_form_submit($form_state) {
  $t=1;

  drupal_set_message(_aakb_writing_competition_t('Thanks for contributing to the writing competition'));
}

/**
 * Translation helper function.
 *
 * @param string $string
 *   The string to translate.
 * @param array $args
 *   Arguments to substitution in the string.
 *
 * @return array|mixed|string|null
 *   The translation.
 */
function _aakb_writing_competition_t($string, $args = []) {
  return t($string, $args, ['context' => 'writing_competition']);
}

function _aakb_writing_competition_get_admin_defaults() {
  return variable_get('aakb_writing_competition', []) + [
    'parent' => [
      'format' => 'ding_wysiwyg',
      'value' => '',
    ],
    'teacher' => [
      'format' => 'ding_wysiwyg',
      'value' => '',
    ],
  ];
}
